In [1]:
install.packages('gtools')

package 'gtools' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\NOTEBOOK\AppData\Local\Temp\Rtmp4MkThY\downloaded_packages


In [2]:
library(gtools)


In [3]:
data <- c('1','2','3')


In [4]:
permutations(3,2,data)


[,1] [,2]
[1,] 1    2   
[2,] 1    3   
[3,] 2    1   
[4,] 2    3   
[5,] 3    1   
[6,] 3    2

In [5]:
combinations(3,2,data)

[,1] [,2]
[1,] 1    2   
[2,] 1    3   
[3,] 2    3

In [6]:
permutations(3,2,data, repeats.allowed = T)


[,1] [,2]
 [1,] 1    1   
 [2,] 1    2   
 [3,] 1    3   
 [4,] 2    1   
 [5,] 2    2   
 [6,] 2    3   
 [7,] 3    1   
 [8,] 3    2   
 [9,] 3    3

In [7]:
combinations(3,2,data, repeats.allowed = T)

[,1] [,2]
[1,] 1    1   
[2,] 1    2   
[3,] 1    3   
[4,] 2    2   
[5,] 2    3   
[6,] 3    3